package app

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	BaseRouter
	CircleRouter
	CircleApplyRouter
	ForumPostsRouter
	GeneralRouter
	ReportRouter
	TopicRouter
	UserRouter
	UserBrowsingHistoryRouter
	UserCollectRouter
	FileUploadAndDownloadRouter

	HkChannelRouter
	HkFocusUserRouter
	HkActivityRouter
	HkActivityClassifyRouter
	HkActivityCollectRouter
	HkActivityUserRouter
	HkUserSignRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
