package community

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AppBaseRouter
	AppUserRouter
	HkForumPostsRouter
	HkCircleRouter
	HkCircleAddRequestRouter
	HkCircleClassifyRouter
	HkCircleRelationRouter
	HkCircleRequestRouter
	HkCircleUserRouter
	HkCommentThumbsUpRouter
	HkForbiddenSpeakRouter
	HkForbiddenSpeakDurationRouter
	HkForbiddenSpeakReasonRouter
	HkForumCommentRouter
	HkForumPostsGroupRouter
	HkForumTagRouter
	HkForumTagGroupRouter
	HkForumThumbsUpRouter
	HkForumTopicRouter
	HkForumTopicGroupRouter
	HkReportRouter
	HkReportReasonRouter
	HkUserCircleApplyRouter
	HkUserExtendRouter
	HkUserRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
