package apply

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	HkApplyRouter
	HkCircleApplyRouter
	HkCircleApplyGroupRouter
	HkPlatApplyRouter
	HkPlatApplyGroupRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
