package general

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	HkBugReportApi
	HkMiniProgramApi
	HkMiniProgramPacketApi
	HkProtocolApi
	HkUserBrowsingHistoryApi
	HkUserCollectApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
