package app

import "github.com/flipped-aurora/gin-vue-admin/server/service"

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AuthApi
	BaseApi
	CircleApi
	CircleApplyApi
	ForumPostsApi
	GeneralApi
	ReportApi
	TopicApi
	UserApi
	UserBrowsingHistoryApi
	UserCollectApi
	FileUploadAndDownloadApi
	FocusApi
	HkChannelApi
	ActivityApi
	QuestionApi
	RecordBrowsingCircleHomepageApi
	RecordBrowsingUserHomepageApi
	WalletApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

var (
	appUserService           = service.ServiceGroupApp.AppServiceGroup.Community.AppUserService
	appCircleService         = service.ServiceGroupApp.AppServiceGroup.Community.AppCircleService
	appCircleRelationService = service.ServiceGroupApp.AppServiceGroup.Community.AppCircleRelationService

	appCircleClassifyService   = service.ServiceGroupApp.AppServiceGroup.Community.AppCircleClassifyService
	appCircleRequestService    = service.ServiceGroupApp.AppServiceGroup.Community.AppCircleRequestService
	appCircleUserService       = service.ServiceGroupApp.AppServiceGroup.Community.AppCircleUserService
	appCircleTagService        = service.ServiceGroupApp.AppServiceGroup.Community.AppCircleTagService
	appCircleAddRequestService = service.ServiceGroupApp.AppServiceGroup.Community.AppCircleAddRequestService
	appCircleChannelService    = service.ServiceGroupApp.AppServiceGroup.Community.AppCircleChannelService

	appForumPostsService      = service.ServiceGroupApp.AppServiceGroup.Community.AppForumPostsService
	appForumCommentService    = service.ServiceGroupApp.AppServiceGroup.Community.AppForumCommentService
	appForumThumbsUpService   = service.ServiceGroupApp.AppServiceGroup.Community.AppForumThumbsUpService
	appCommentThumbsUpService = service.ServiceGroupApp.AppServiceGroup.Community.AppCommentThumbsUpService

	appForumTopicGroupService = service.ServiceGroupApp.AppServiceGroup.Community.AppForumTopicGroupService
	appForumTopicService      = service.ServiceGroupApp.AppServiceGroup.Community.AppForumTopicService

	appReportService                      = service.ServiceGroupApp.AppServiceGroup.Community.AppReportService
	appReportReasonService                = service.ServiceGroupApp.AppServiceGroup.Community.AppReportReasonService
	appUserCircleApplyService             = service.ServiceGroupApp.AppServiceGroup.Community.AppUserCircleApplyService
	hkRecordBrowsingCircleHomepageService = service.ServiceGroupApp.AppServiceGroup.Community.RecordBrowsingCircleHomepageService
	hkRecordBrowsingUserHomepageService   = service.ServiceGroupApp.AppServiceGroup.Community.RecordBrowsingUserHomepageService

	appProtocolService            = service.ServiceGroupApp.AppServiceGroup.General.AppProtocolService
	appBugReportService           = service.ServiceGroupApp.AppServiceGroup.General.AppBugReportService
	appUserCollectService         = service.ServiceGroupApp.AppServiceGroup.General.AppUserCollectService
	appUserBrowsingHistoryService = service.ServiceGroupApp.AppServiceGroup.General.AppUserBrowsingHistoryService
	appMiniProgramService         = service.ServiceGroupApp.AppServiceGroup.General.AppMiniProgramService

	appApplyService            = service.ServiceGroupApp.AppServiceGroup.Apply.AppApplyService
	appCircleApplyService      = service.ServiceGroupApp.AppServiceGroup.Apply.AppCircleApplyService
	appCircleApplyGroupService = service.ServiceGroupApp.AppServiceGroup.Apply.AppCircleApplyGroupService

	fileUploadAndDownloadService = service.ServiceGroupApp.ExampleServiceGroup.FileUploadAndDownloadService
	jwtService                   = service.ServiceGroupApp.SystemServiceGroup.JwtService
	cacheSmsService              = service.ServiceGroupApp.SystemServiceGroup.CacheSmsService

	hkActivityAddRequestService = service.ServiceGroupApp.AppServiceGroup.Community.ActivityAddRequestService
	hkThirdPlatformService      = service.ServiceGroupApp.AppServiceGroup.Community.ThirdPlatformService
	hkGoldBillService           = service.ServiceGroupApp.AppServiceGroup.Community.GoldBillService
	hkOrderService              = service.ServiceGroupApp.AppServiceGroup.Community.OrderService
	hkUserBillService           = service.ServiceGroupApp.AppServiceGroup.Community.UserBillService
	hkUserExtractService        = service.ServiceGroupApp.AppServiceGroup.Community.HkUserExtractService
	hkUserRechargeService       = service.ServiceGroupApp.AppServiceGroup.Community.UserRechargeService

	//apiService              = service.ServiceGroupApp.SystemServiceGroup.ApiService
	//jwtService              = service.ServiceGroupApp.SystemServiceGroup.JwtService
	//menuService             = service.ServiceGroupApp.SystemServiceGroup.MenuService
	//userService             = service.ServiceGroupApp.SystemServiceGroup.UserService
	//initDBService           = service.ServiceGroupApp.SystemServiceGroup.InitDBService
	//casbinService           = service.ServiceGroupApp.SystemServiceGroup.CasbinService
	//autoCodeService         = service.ServiceGroupApp.SystemServiceGroup.AutoCodeService
	//baseMenuService         = service.ServiceGroupApp.SystemServiceGroup.BaseMenuService
	//authorityService        = service.ServiceGroupApp.SystemServiceGroup.AuthorityService
	//dictionaryService       = service.ServiceGroupApp.SystemServiceGroup.DictionaryService
	//systemConfigService     = service.ServiceGroupApp.SystemServiceGroup.SystemConfigService
	//operationRecordService  = service.ServiceGroupApp.SystemServiceGroup.OperationRecordService
	//autoCodeHistoryService  = service.ServiceGroupApp.SystemServiceGroup.AutoCodeHistoryService
	//dictionaryDetailService = service.ServiceGroupApp.SystemServiceGroup.DictionaryDetailService
	//authorityBtnService     = service.ServiceGroupApp.SystemServiceGroup.AuthorityBtnService
)
