package app

import "github.com/flipped-aurora/gin-vue-admin/server/service"

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	UserApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

var (
	hkUserService           = service.ServiceGroupApp.CommunityServiceGroup.HkUserService
	hkCircleService         = service.ServiceGroupApp.CommunityServiceGroup.HkCircleService
	hkCircleClassifyService = service.ServiceGroupApp.CommunityServiceGroup.HkCircleClassifyService
	hkCircleRequestService  = service.ServiceGroupApp.CommunityServiceGroup.HkCircleRequestService
	hkCircleUserService     = service.ServiceGroupApp.CommunityServiceGroup.HkCircleUserService

	hkForumPostsService      = service.ServiceGroupApp.CommunityServiceGroup.HkForumPostsService
	hkForumCommentService    = service.ServiceGroupApp.CommunityServiceGroup.HkForumCommentService
	hkForumThumbsUpService   = service.ServiceGroupApp.CommunityServiceGroup.HkForumThumbsUpService
	hkCommentThumbsUpService = service.ServiceGroupApp.CommunityServiceGroup.HkCommentThumbsUpService

	hkForumTopicGroupService = service.ServiceGroupApp.CommunityServiceGroup.HkForumTopicGroupService
	hkForumTopicService      = service.ServiceGroupApp.CommunityServiceGroup.HkForumTopicService

	hkReportService       = service.ServiceGroupApp.CommunityServiceGroup.HkReportService
	hkReportReasonService = service.ServiceGroupApp.CommunityServiceGroup.HkReportReasonService

	hkProtocolService  = service.ServiceGroupApp.GeneralServiceGroup.HkProtocolService
	hkBugReportService = service.ServiceGroupApp.GeneralServiceGroup.HkBugReportService

	hkApplyService            = service.ServiceGroupApp.ApplyServiceGroup.HkApplyService
	hkCircleApplyService      = service.ServiceGroupApp.ApplyServiceGroup.HkCircleApplyService
	hkUserCircleApplyService  = service.ServiceGroupApp.CommunityServiceGroup.HkUserCircleApplyService
	hkCircleApplyGroupService = service.ServiceGroupApp.ApplyServiceGroup.HkCircleApplyGroupService

	hkUserCollectService         = service.ServiceGroupApp.GeneralServiceGroup.HkUserCollectService
	hkUserBrowsingHistoryService = service.ServiceGroupApp.GeneralServiceGroup.HkUserBrowsingHistoryService

	jwtService      = service.ServiceGroupApp.SystemServiceGroup.JwtService
	cacheSmsService = service.ServiceGroupApp.SystemServiceGroup.CacheSmsService
	//apiService              = service.ServiceGroupApp.SystemServiceGroup.ApiService
	//jwtService              = service.ServiceGroupApp.SystemServiceGroup.JwtService
	//menuService             = service.ServiceGroupApp.SystemServiceGroup.MenuService
	//userService             = service.ServiceGroupApp.SystemServiceGroup.UserService
	//initDBService           = service.ServiceGroupApp.SystemServiceGroup.InitDBService
	//casbinService           = service.ServiceGroupApp.SystemServiceGroup.CasbinService
	//autoCodeService         = service.ServiceGroupApp.SystemServiceGroup.AutoCodeService
	//baseMenuService         = service.ServiceGroupApp.SystemServiceGroup.BaseMenuService
	//authorityService        = service.ServiceGroupApp.SystemServiceGroup.AuthorityService
	//dictionaryService       = service.ServiceGroupApp.SystemServiceGroup.DictionaryService
	//systemConfigService     = service.ServiceGroupApp.SystemServiceGroup.SystemConfigService
	//operationRecordService  = service.ServiceGroupApp.SystemServiceGroup.OperationRecordService
	//autoCodeHistoryService  = service.ServiceGroupApp.SystemServiceGroup.AutoCodeHistoryService
	//dictionaryDetailService = service.ServiceGroupApp.SystemServiceGroup.DictionaryDetailService
	//authorityBtnService     = service.ServiceGroupApp.SystemServiceGroup.AuthorityBtnService
)
