package general

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	HkBugReportService
	HkMiniProgramService
	HkMiniProgramPacketService
	HkProtocolService
	HkUserBrowsingHistoryService
	HkUserCollectService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
