package apply

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	HkApplyApi
	HkCircleApplyApi
	HkCircleApplyGroupApi
	HkPlatApplyApi
	HkPlatApplyGroupApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
