package apply


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	HkApplyService
	HkCircleApplyService
	HkCircleApplyGroupService
	HkPlatApplyService
	HkPlatApplyGroupService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

