package app

import (
	"github.com/flipped-aurora/gin-vue-admin/server/service/app/apply"
	"github.com/flipped-aurora/gin-vue-admin/server/service/app/community"
	"github.com/flipped-aurora/gin-vue-admin/server/service/app/general"
)

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	Apply     apply.ServiceGroup
	Community community.ServiceGroup
	General   general.ServiceGroup
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
