package community

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	HkForumPostsService
	HkCircleService
	HkCircleAddRequestService
	HkCircleClassifyService
	HkCircleRelationService
	HkCircleRequestService
	HkCircleUserService
	HkCommentThumbsUpService
	HkForbiddenSpeakService
	HkForbiddenSpeakDurationService
	HkForbiddenSpeakReasonService
	HkForumCommentService
	HkForumPostsGroupService
	HkForumTagService
	HkForumTagGroupService
	HkForumThumbsUpService
	HkForumTopicService
	HkForumTopicGroupService
	HkReportService
	HkReportReasonService
	HkUserCircleApplyService
	HkUserExtendService
	HkUserService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
