package general

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AppMiniProgramService
	AppMiniProgramPacketService
	AppProtocolService
	AppVersionService
	AppUserBrowsingHistoryService
	AppUserCollectService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
