package apply

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AppApplyService
	AppCircleApplyService
	AppCircleApplyGroupService
	AppPlatApplyService
	AppPlatApplyGroupService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
