package community

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AppForumPostsService
	AppCircleService
	AppCircleAddRequestService
	AppCircleClassifyService
	AppCircleRelationService
	AppCircleRequestService
	AppCircleUserService
	AppCommentThumbsUpService
	AppForbiddenSpeakService
	AppForbiddenSpeakDurationService
	AppForbiddenSpeakReasonService
	AppForumCommentService
	AppForumTagService
	AppForumTagGroupService
	AppForumThumbsUpService
	AppForumTopicService
	AppForumTopicGroupService
	AppReportService
	AppReportReasonService
	AppUserCircleApplyService
	AppUserExtendService
	AppUserService
	AppForumTopicPostsMappingService
	HkChannelService
	FocusUserService
	ActivityService
	ActivityUserService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
