package community

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AppForumPostsService
	AppCircleService
	AppCircleAddRequestService
	AppCircleClassifyService
	AppCircleRelationService
	AppCircleRelationRequestService
	AppCircleRequestService
	AppCircleUserService
	AppCircleTagService
	AppCircleChannelService
	AppCommentThumbsUpService
	AppForbiddenSpeakService
	AppForbiddenSpeakDurationService
	AppForbiddenSpeakReasonService
	AppForumCommentService
	AppForumTagService
	AppForumTagGroupService
	AppForumThumbsUpService
	AppForumTopicService
	AppForumTopicGroupService
	AppReportService
	AppReportReasonService
	AppUserExtendService
	AppUserService
	AppForumTopicPostsMappingService
	HkChannelService
	FocusUserService
	ActivityService
	QuestionService
	ActivityUserService
	ActivityAddRequestService
	ThirdPlatformService
	RecordBrowsingCircleHomepageService
	RecordBrowsingUserHomepageService
	GoldBillService
	UserBillService
	UserCoverImageService
	UserHeaderImageService
	UserRechargeService
	HkUserExtractService
	OrderService
	ProductGoldService
	PayTypeService
	ExtractTypeService
	HelpTypeService
	HelpService
	FeedbackService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
