package initialize

import (
	"github.com/flipped-aurora/gin-vue-admin/server/model/apply"
	"github.com/flipped-aurora/gin-vue-admin/server/model/general"
	"os"

	"github.com/flipped-aurora/gin-vue-admin/server/global"
	"github.com/flipped-aurora/gin-vue-admin/server/model/example"
	"github.com/flipped-aurora/gin-vue-admin/server/model/system"

	"github.com/flipped-aurora/gin-vue-admin/server/model/community"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Gorm 初始化数据库并产生数据库全局变量
// Author SliverHorn
func Gorm() *gorm.DB {
	switch global.GVA_CONFIG.System.DbType {
	case "mysql":
		return GormMysql()
	case "pgsql":
		return GormPgSql()
	case "oracle":
		return GormOracle()
	case "mssql":
		return GormMssql()
	default:
		return GormMysql()
	}
}

// RegisterTables 注册数据库表专用
// Author SliverHorn
func RegisterTables(db *gorm.DB) {
	err := db.AutoMigrate(
		// 系统模块表
		system.SysApi{},
		system.SysUser{},
		system.SysBaseMenu{},
		system.JwtBlacklist{},
		system.SysAuthority{},
		system.SysDictionary{},
		system.SysOperationRecord{},
		system.SysAutoCodeHistory{},
		system.SysDictionaryDetail{},
		system.SysBaseMenuParameter{},
		system.SysBaseMenuBtn{},
		system.SysAuthorityBtn{},
		system.SysAutoCode{},

		// 示例模块表
		example.ExaFile{},
		example.ExaCustomer{},
		example.ExaFileChunk{},
		example.ExaFileUploadAndDownload{},

		// 自动化模块表
		// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
		//社区
		community.HkForumPosts{},
		community.HkCircle{},
		community.HkCircleAddRequest{},
		community.HkCircleClassify{},
		community.HkCircleRelation{},
		community.HkCircleRequest{},
		community.HkCircleUser{},
		community.HkCommentThumbsUp{},
		community.HkForbiddenSpeak{},
		community.HkForbiddenSpeakDuration{},
		community.HkForbiddenSpeakReason{},
		community.HkForumComment{},
		community.HkForumPostsGroup{},
		community.HkForumTag{},
		community.HkForumTagGroup{},
		community.HkForumThumbsUp{},
		community.HkForumTopic{},
		community.HkForumTopicGroup{},
		community.HkReport{},
		community.HkUserCircleApply{},
		community.HkReportReason{},
		community.HkUserExtend{},
		community.HkUser{},
		//应用
		apply.HkApply{},
		apply.HkCircleApply{},
		apply.HkCircleApplyGroup{},
		apply.HkPlatApply{},
		apply.HkPlatApplyGroup{},
		//常规业务
		general.HkMiniProgram{},
		general.HkMiniProgramPacket{},
		general.HkProtocol{},
		general.HkBugReport{},
		general.HkUserCollect{},
		general.HkUserBrowsingHistory{},
		// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	)
	if err != nil {
		global.GVA_LOG.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.GVA_LOG.Info("register table success")
}
